### ISSUE TITLE
Inadequate setup instructions

### ISSUE THREAD

**Issue by palaparthi** [nodu/teamster#1]
@nodu I am following the instructions in readme, but was unable to get the setup working. After installing Nix, running `shell-nix` gives me a command not found. Can you please update the setup instructions in readme on how to setup the project steb by step, thanks.

**Comment by nodu** [comment]
Hi @palaparthi, I've just pushed a commit refining the setup instructions. Let me know how it goes!

**Comment by palaparthi** [comment]
@nodu I am still having issues with the setup, is there any way you could dockerize this? thank you!

**Comment by nodu** [comment]
Hi @palaparthi, I'm quite curious as to what issues you're having; however, I've hacked together a docker compose for you so you can play around with the live app. You can launch the app with `docker compose up`. 

This should pull the images from docker hub, as you won't likely be able to build the images locally since you're having issues setting up nix on your local. I've double checked the original setup instructions and running 'docker compose up' on several new machines. So I hope it works for you, Thanks! (If not please share the logs.)
